### PR TITLE
First try for a user-friendly UI

### PR DESCRIPTION
**Pull request by sdobbs**
Added new script to display and build "official" releases

### CODE REVIEW

**Comment by markito3** [comment]
This builds everything, no?

**Comment by sdobbs** [comment]
That's correct.  I assume that build_scripts won't rebuild a package if it already exists.  I hope this is a good assumption?

**Comment by markito3** [comment]
It should not do a re-build, but I have memories of packages rebuilding when they should not have, occasionally and not always. It is one of those things I have never been able to nail down precisely.

**Comment by sdobbs** [comment]
Yeah, you can also do something like leaving a ".success" file in the directories that built correctly and then checking for that, but this is also not foolproof (had problems with hdpm with this sometimes).  So probably... there is no perfect solution.

**Pull request merged**
